[package]
name = "ex_vl_convert"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "ex_vl_convert"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.35.0"
vl-convert-rs = "1.6.0"
serde_json = "1.0.120"
futures = "0.3.30"
